import { NgModule } from '@angular/core';
import { MatSnackBarModule } from '@angular/material/snack-bar';

@NgModule({
  declarations: [
    // ... existing code ...
  ],
  imports: [
    // ... existing code ...
    MatSnackBarModule,
    // ... existing code ...
  ],
  // ... existing code ...
})
// ... existing code ... 